source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

def sharedPods
    pod 'ALDataRequestView', :path => '../'
    pod 'ALDataRequestView/ReactiveCocoa', :path => '../'
    pod 'ALDataRequestView/RxSwift', :path => '../'
end

target 'ALDataRequestView_Example' do
    sharedPods
end

target 'ALDataRequestView_Tests' do
    sharedPods
end
